[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
included_files = ["src/**/*"]

[functions."upload-cert"]
  external_node_modules = ["node-forge"]

[build.environment]
  NODE_VERSION = "18"